version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/sql_commands
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
